# part 1
# walker interact {
#     can return_message with `root entry {
#         report {
#             "response": "Hello, world!"
#         };
#     }
# }

# walker interact_with_body {
#     has name: str;

#     can return_message with `root entry {
#         report {
#             "response": "Hello, " + self.name + "!"
#         };
#     }
# }

# 2 new walkers for part 1
# walker get_day_of_week {
#     has weekday: int;  # Weekday number where Sunday = 0, Monday = 1, ..., Saturday = 6

#     can return_message with `root entry {
#         let days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
#         let day_of_week = days[self.weekday];

#         report {
#             "response": "The day of the week is " + day_of_week + "."
#         };
#     }
# }



# walker calculate_age {
#     has birth_year: int;
#     has current_year: int;

#     can return_message with `root entry {
#         let age = str(self.current_year - self.birth_year);

#         report {
#             "response": "You are " + age + " years old."
#         };
#     }
# }


# part 2


import:py from mtllm.llms {Ollama}

glob llm = Ollama(model_name='llama3.1');

import:jac from rag {RagEngine}
glob rag_engine:RagEngine = RagEngine();

node Session {
    has id: str;
    has chat_history: list[dict];
    has status: int = 1;

    can 'Respond to message using chat_history as context and agent_role as the goal of the agent'
    llm_chat(
        message:'current message':str,
        chat_history: 'chat history':list[dict],
        agent_role:'role of the agent responding':str,
        context:'retrieved context from documents':list
    ) -> 'response':str by llm();
}

walker interact {
    has message: str;
    has session_id: str;

    can init_session with `root entry {
         visit [-->](`?Session)(?id == self.session_id) else {
            session_node = here ++> Session(id=self.session_id, chat_history=[], status=1);
            print("Session Node Created");

            visit session_node;
        }
    }
    can chat with Session entry {
        here.chat_history.append({"role": "user", "content": self.message});
        data = rag_engine.get_from_chroma(query=self.message);
        response = here.llm_chat(
            message=self.message,
            chat_history=here.chat_history,
            agent_role="You are a conversation agent designed to help users with their queries based on the documents provided",
            context=data
        );

        here.chat_history.append({"role": "assistant", "content": response});

        report {"response": response};
    }
}


